### ISSUE TITLE
DiscountRate and DiscountStart 

### ISSUE THREAD

**Issue by MechFroG88** [AY2122S2-CS2103T-T09-4/tp#147]
**Describe the bug**

DiscountRate and DiscountStart should be optional, but not providing both of them will result in an error.

**To Reproduce**

`add n:hello p:1.3`

**Expected behavior**

A new product should be added

**Comment by 1001mei** [comment]
> **To Reproduce**
> 
> `add n:hello p:1.3`

I think this error resulted from the fact that c:CATEGORY and d:DESCRIPTION is not provided, not the discount functionality fault.

For example, 
`add n: hello c:cheese p:1.20 d:testing` works just fine
