### ISSUE TITLE
[PE-D] `update-all` seems to not be useful for updating more than one name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T09-4/tp#209]
![image.png](https://raw.githubusercontent.com/Spyobird/ped/main/files/dc3753c1-22c1-4d87-9dc3-46206b677402.png)

`update-all n:someName`
Updating the name of more than one item does not work with this command, understandably. So the feature does not seem best suited for this.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Spyobird/ped#10

**Comment by MechFroG88** [comment]
Not a bug
