### ISSUE TITLE
[PE-D] update-all will auto cancel the filter

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T09-4/tp#211]
![image.png](https://raw.githubusercontent.com/ddx-510/ped/main/files/f836c35f-cfc9-4501-91e0-c1dafdbe8542.png)

Currently, the filter is showcasing out-of-stock products
After editing the categories to all listed products, the filter will automatically disappear.

![image.png](https://raw.githubusercontent.com/ddx-510/ped/main/files/f34b8291-cd1f-49f7-8b2c-8ce24ecf1230.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: ddx-510/ped#7

**Comment by 1001mei** [comment]
Intended behavior.
