### ISSUE TITLE
Create an Item object

### ISSUE THREAD

**Issue by mazx4960** [AY2122S2-CS2103T-T09-4/tp#36]
The current `Product` object involves creating a new instance for every item. However, many fields in the `Product` class are repeated for the same items.

**Proposed changes:**
- Create a new `Item` class which encapsulates: 
  - `Product`: the product that the item belongs to
  - `ExpiryDate`: same as before
  - `Count`: the number of items that belong to the same product and has the same expiry date
- Modify `Product` class to include only the fields: `Name`, `Category`, `Description`, `Price` and additionally a list of **`Item`s**

**Comment by DavidTan0527** [comment]
> ...additionally a list of `Item`s

This can be implemented as `PriorityQueue<Item>` as to sort by `ExpiryDate`.

Furthermore, there should be a field for discounted price and the number of days within the expiry date in which the discount is effective. Then, we can probably abstract this checking process using a method in `Item`.
